# Generated by Django 5.2.1 on 2025-08-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpromotion',
            name='active_dates_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodpromotion',
            name='deal_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodpromotion',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='telefoodpromos_photos/'),
        ),
    ]
